### ISSUE TITLE
vimnotes page: YT videos unavailable 

### ISSUE THREAD

**Issue by ahndmal** [jshin313/site#2]
Hello @jshin313,
Thanks a lot for your work and nice information on your site! :)
I cannot access YT videos on https://github.com/jshin313/site/blob/main/content/posts/vimnotes.md

![image](https://user-images.githubusercontent.com/36703491/214554570-e52ad526-58e7-46b1-8db0-51c6b8179cb0.png)

Would be great to have this fixed.

Thank you!

**Comment by jshin313** [comment]
It looks like the primeagen took some of the videos private or deleted them. 

I took these notes a few years ago, but now the primeagen has a new vim series:
 https://youtube.com/playlist?list=PLm323Lc7iSW_wuxqmKx_xxNtJC_hJbQ7R
